### ISSUE TITLE
figure out how to run headless

### ISSUE THREAD

**Issue by bradphelan** [bradphelan/jasminerice#1]
We need a rake task

rake jasmine:ci

that will spit out the results of the tests automagically.

**Comment by jsmestad** [comment]
Would love to see this added.

**Comment by netzpirat** [comment]
After I discovered Jasminerice yesterday, I tought I could make a [Guard](https://github.com/guard/guard) for headless testing, and here it is: [Guard::Jasmine](https://github.com/netzpirat/guard-jasmine).

It uses PhantomJS to get the Jasmine tests (integrated with Jasminerice) from the Rails app and runs them headless, giving feedback in the console and with system notifications. With Guard everything can be configured and scripted to your needs, so you can define what get tested when something is modified.

Have phun...

**Comment by bradphelan** [comment]
Brilliant. Can't wait to give it a spin :)
On Sep 7, 2011 6:36 PM, "Michael Kessler" <
reply@reply.github.com>
wrote:

**Comment by jmaicher** [comment]
@netzpirat That's awesome! Works like a charm..

It should be possible to create a rake task which makes use of PhantomJS and runs the jasmine tests only once, right?

**Comment by netzpirat** [comment]
Yes absolutely. You could simple modify the [Jasmine runner script](https://github.com/netzpirat/guard-jasmine/blob/master/lib/guard/jasmine/phantomjs/run-jasmine.coffee) to output a real message instead of a JSON protocol, and just use the Rake task as a wrapper to call PhantomJS with the script.

**Comment by avocade** [comment]
+1 Would be awesome to have something like "rake jasmine:ci" running with headless webkit (see capybara-webkit).

**Comment by sveinn** [comment]
+1 on 'rake jasmine:ci'

**Comment by huynguyen** [comment]
+1 on `rake jasmine:ci`

I've been trying to do this, any comments/hints on where to start?

**Comment by bradphelan** [comment]
I've updated the doc to indicate the third party gem that makes this possible.
