### ISSUE TITLE
Fixtures being cached

### ISSUE THREAD

**Issue by saadullahsaeed** [bradphelan/jasminerice#105]
Seems like my changes to the fixture are not being reflected, is there a configuration to disable caching of fixtures?

**Comment by jejacks0n** [comment]
Just an ajax caching issue?

**Comment by saadullahsaeed** [comment]
Actually, I realized after posting that I was editing the wrong file (same name, another path), felt really stupid. But yeah :)

**Comment by jejacks0n** [comment]
D'oh!  I hate when I do stuff like that. ;-P
