### ISSUE TITLE
Problem with patched jasmine-jquery

### ISSUE THREAD

**Issue by runiie** [bradphelan/jasminerice#114]
After running the test examples i got this error:

00:02:14 - INFO - Foo
00:02:14 - INFO -   ✘ encountered a declaration exception
00:02:14 - INFO -     ➤ ReferenceError: Can't find variable: $ in jasmine-jquery-1.5.2.js on line 146
00:02:14 - INFO -     ➤ ReferenceError: Can't find variable: $ in jasmine-jquery-1.5.2.js on line 146
00:02:14 - ERROR - 1 spec, 2 failures

And so on to every test. ps: using rails 4.

**Comment by DronRathore** [comment]
Hey @wallacyyy, did you figured out what was wrong? I am into the same problem.
