### ISSUE TITLE
How to use in Jenkins/CI environment

### ISSUE THREAD

**Issue by cayblood** [bradphelan/jasminerice#116]
Any suggestions for how best to run my jasminerice tests from the command line so that I can run them in a jenkins build? I have erb templates in my js files so I need them to be served from rails.

**Comment by johnnymugs** [comment]
Comment by @jeffsaracco https://github.com/bradphelan/jasminerice/issues/53#issuecomment-14858881 might have what you are looking for.

**Comment by jejacks0n** [comment]
It's been mentioned around as well, but you may want to check out [Teaspoon](https://github.com/modeset/teaspoon). (full disclosure, I wrote it).  But it has reporters and uses phantomjs to run them via command line.  I usually add teaspoon to the default rake task so it runs after my ruby specs, and before cucumber/acceptance tests.
