### ISSUE TITLE
The jasminerice gem is out of date

### ISSUE THREAD

**Issue by elbowdonkey** [bradphelan/jasminerice#118]
Currently if one installs the latest jasminerice Ruby gem, they'll be installing dated code. 

Since the gem isn't being pushed to rubygems.org all the improvements made since the gem was first published aren't available unless one points to the repo here as the source. But there's a catch - if someone installed the rubygems.org version of the gem (which is a fairly likely scenario), then points to this repo as the source in a Gemfile, for example, they still won't get any updates since the version number remains the same as the cached gem that's likely sitting on their machine.

I'm guessing @bradphelan would need to push the new gem after bumping the gem spec version number up.

**Comment by elbowdonkey** [comment]
Zoiks! I knew it was likely that I was duping an issue, namely #86. I think, if anything, this is probably the time when we move jasminerice to a new home. If people are working on this project, it's gonna get updates to master. New gem versions need to be pushed when master is updated.

With that in mind, I'd be happy to maintain this project.

**Comment by jejacks0n** [comment]
Thanks for the offer.. I never heard back from him about transferring the gem (or removing it) so we could push it.

If you read the issue you referenced (#86), you'll see all of that information and my recommendation.

I have collaboration, so I can merge your pull request for a version update -- which will resolve part of your issue, but yeah, without the ability to release the gem, we'd have to rename the gem to be able to release a new one -- which sort of defeats the purpose. :-/
