### ISSUE TITLE
Use jasmine-core

### ISSUE THREAD

**Issue by maxcal** [bradphelan/jasminerice#122]
Would it be possible use the javascript files from [jasmine-core](https://rubygems.org/gems/jasmine-core)? I was somewhat suprised when I started up `http://localhost:3000/jasmine` and it was using version 1.3.1 instead of 2.0.2 which was included by the [jasmine gem](https://rubygems.org/gems/jasmine).

PS. Thanks for the great work with `jasminerice`.

**Comment by jejacks0n** [comment]
probably not unless you submit a pull request. I barely have time to maintain teaspoon at the moment.

**Comment by maxcal** [comment]
After some digging I got the jasmine gem working with the rails asset pipeline without jasminerice. Closing this issue since I don´t really see a reason to use it. Thanks anyways
