### ISSUE TITLE
document.write in spec breaks jasmine page

### ISSUE THREAD

**Issue by laripk** [bradphelan/jasminerice#15]
I'm using jasminerice 0.0.7 with guard-jasmine 0.7.2. I ran into a problem with guard-jasmine timing out ( https://github.com/netzpirat/guard-jasmine/issues/5 ) and eventually traced it to being caused by a test in which I had a `document.write` - example: https://gist.github.com/1322112 .

Then I started checking the test in my browser (Chrome 14.0.835.202) and found that the `document.write` was blowing away the entire document body see https://gist.github.com/1322112 .

I have since changed my test to use `$('body').append` (jquery), but I thought you should know about it, or at least document it for others.

**Comment by bradphelan** [comment]
Not sure what you can say about this. Jasmine is loaded into the DOM. It's not loaded as some plugin to the browser. If in your tests you blow away the DOM completely then this is what you would expect.

**Comment by laripk** [comment]
I didn't know that `document.write` blew away the DOM. I thought it added stuff in the middle. Anyway, I know better now. Thanks.
