### ISSUE TITLE
ReferenceError: Can't find variable: jQuery

### ISSUE THREAD

**Issue by svendahlstrand** [bradphelan/jasminerice#26]
```
ReferenceError: Can't find variable: jQuery in http://localhost:3000/assets/jasmine-jquery-1.3.1.js?body=1 (line 67)
```

I got this error when following the instructions in the README for jasminerice 0.0.8. jasminerice-jquery is dependent on jQuery so I added `#=require jquery` to the spec.js.coffee file and it solved the problem.

Shouldn't this dependency be met automatically? If thats not the case: maybe update the README with instructions?

**Comment by gmassanek** [comment]
I ran into the same error, and @svendahlstrand had the right suggestion to fix it.

**Comment by brianhempel** [comment]
I also ran into this. Thanks @svendahlstrand for the fix.

**Comment by Shamaoke** [comment]
If your `spec.js.coffee` points on the `app/assets/javascripts` directory where the `application.js` file with `//= require jquery` is, it's not necessary to add `#= require jquery` once more.

For example, in the following case:

**spec/javascripts/spec.js.coffee**

```
#= require_tree .
#= require_tree ../../app/assets/javascripts
```

**app/assets/javascripts/application.js**

```
//= require jquery
```

there's no need to add `#= require jquery` in the first file one more time, it's already be done.

**Comment by bradphelan** [comment]
jasmine-jquery doesn't 'require' jquery so you have to include it yourself manually.
