### ISSUE TITLE
Add coffee-rails to gem runtime dependencies

### ISSUE THREAD

**Issue by alekseykulikov** [bradphelan/jasminerice#27]
Something like this:
s.add_dependency( 'haml' , 'coffee-rails')

I can't used gem without 'coffee-rails' in my Gemfile. It's need for compiling .coffee files in jasminerice. For example: jasminerice.js.coffee

**Comment by mdavidn** [comment]
This burned me too. I don't use CoffeeScript in my project, but I'd still like to use the asset pipeline in my Jasmine tests.

I worked around this issue by manually dropping JavaScript versions of the Jasminerice scripts in vendor/assets.
