### ISSUE TITLE
Jasmine 1.2.0.rc1 is already out

### ISSUE THREAD

**Issue by phuongnd08** [bradphelan/jasminerice#29]
Jasmine 1.2.0.rc1 is out with pretty cool UI. I would love to see it is available with jasminerice also.

**Comment by netzpirat** [comment]
I don't think it's a good idea to add a release candidate, this may break some specs. But you can simply put the RC into your Rails projects `vendor/assets/javascript`.

**Comment by bmaland** [comment]
Jasmine 1.2.0 final is out now, a new release would be nice!
