### ISSUE TITLE
How to run the specs in CI?

### ISSUE THREAD

**Issue by dnagir** [bradphelan/jasminerice#31]
I wonder if there is any way to run all of the Jasminerice specs through rake on a CI server?

The `jasmine:ci` has totally separate configuration and has no access to the Rails assets.

Any suggestions? Or maybe it's already possible?

**Comment by bradphelan** [comment]
THere is a project on.github that integrates jasminerice with a ci:server.
I even think I added a link to it on the main readme.
On Jan 28, 2012 8:21 AM, "Dmytrii Nagirniak" <
reply@reply.github.com>
wrote:

**Comment by bradphelan** [comment]
https://github.com/netzpirat/guard-jasmine

**Comment by dnagir** [comment]
Right. I got a confused because `guard-jasmine` is mostly used with Guard on dev machine.

I wonder how you integrate it with your CI usually.

This is what I do now from a Rake task.

``` ruby
# lib/tasks/ci.rake
task :ci do
  Rake::Task['spec'].invoke
  ensure_test_coverage 99
  Rake::Task['cucumber'].invoke
  Guard::Jasmine::CLI.start # Is it the right way to do it???
end
```

**Comment by netzpirat** [comment]
Guard Jasmine comes now with Rake task integration:

Simply create a JasmineTask within your `Rakefile`:

``` ruby
require 'guard/jasmine/task'
Guard::JasmineTask.new
```

You can configure the CLI options either by providing the options as parameter or use a block:

``` ruby
require 'guard/jasmine/task'

Guard::JasmineTask.new do |task|
  task.options = '-t 15 -e test'
end

Guard::JasmineTask.new(:jasmine_no_server, '-s none')
```

You can also use it directly from the command line:

``` bash
$ guard-jasmine
```

You can get help on the available options with the help task:

```
$ guard-jasmine help spec

Usage:
  guard-jasmine spec

Options:
  -s, [--server=SERVER]          # Server to start, either `auto`, `none`, `webrick`, `mongrel`, `thin`, `jasmine_gem`
                                 # Default: auto
  -p, [--port=N]                 # Server port to use
                                 # Default: 8888
  -u, [--url=URL]                # The url of the Jasmine test runner
                                 # Default: http://127.0.0.1:8888/jasmine
  -b, [--bin=BIN]                # The location of the PhantomJS binary
                                 # Default: /usr/local/bin/phantomjs
  -t, [--timeout=N]              # The maximum time in milliseconds to wait for the spec runner to finish
                                 # Default: 10000
  -c, [--console=CONSOLE]        # Whether to show console.log statements in the spec runner, either `always`, `never` or `failure`
                                 # Default: failure
  -e, [--server-env=SERVER_ENV]  # The server environment to use, for example `development`, `test` etc.
                                 # Default: test

Run the Jasmine spec runner
```

**Comment by bradphelan** [comment]
Thanks for the info netzpirat!

**Comment by dnagir** [comment]
@netzpirat  Thanks a lot for the info.
