### ISSUE TITLE
Asset Pipeline not being invoked for non /jasmine route

### ISSUE THREAD

**Issue by dagda1** [bradphelan/jasminerice#37]
I have installed jasminerice in my gem file like this:

group :test, :development do
  gem 'jasminerice'

My spec/javascripts/spec.js.coffee looks like this
# =require ../../app/assets/javascripts/application
# =require_tree ./

I had to explicitly reference my application. js file while all the examples show the spec.js.coffee looking like this:
# =require application

My specs all run when I go through the /jasmine route but the application.js and application.css are not being compiled when I run through a non /jasmine route.

It works fine if I remove the jasmine rice gem from the gem file.

Is there anything obvious I am doing wrong?  I am running rails 3.2.2.

**Comment by bradphelan** [comment]
It is correct that you should only have to do

```
#=require application
```

as the app/assets/javascripts directory should be on the load path of the asset pipeline.
