### ISSUE TITLE
There shouldn't be a notification when I have no Jasminerice::HelperMethods

### ISSUE THREAD

**Issue by jmaicher** [bradphelan/jasminerice#38]
```
Declare your Jasminerice::HelperMethods (perhaps put inside lib/) to make helpers available to jasminerice fixtures
```

This notification is useless and has been introduced with #32.
It should be mentioned in the documentation that helper methods are possible.

**Comment by bradleypriest** [comment]
Yeah +1 this is not a useful feature

**Comment by monolar** [comment]
+1
I agree that this is not useful. Write it up in the docs or changelog. Using begin/rescue should not be used to announce features.
