### ISSUE TITLE
Can't customise index.html.haml file

### ISSUE THREAD

**Issue by alexslade** [bradphelan/jasminerice#39]
I'd like to add some extra elements to the html file my specs are being run in. 

Currently, I have to put this custom file in /app/views/jasminerice/spec/index.html.haml

I'd like to be able to just put that in my javascript/spec folder, like you can with CSS. Shall I put together a patch, or is this possible at the moment?

**Comment by jejacks0n** [comment]
If you want this badly enough, you can modify the controller to render the view from wherever you'd like.
