### ISSUE TITLE
undefined reference jQuery

### ISSUE THREAD

**Issue by ohcibi** [bradphelan/jasminerice#47]
I followed your instructions and wrote a simple failing test in coffeescript. The test fails as expected but i also get an "ReferenceError: jQuery is not defined at [object Object].cleanUp (http://localhost:3000/assets/jasmine-jquery-1.3.1.js?body=1:67:3)" error.

I then put `#=require application` in spec.js.coffee (which in fact requires a copy of jQuery for the application itself) and the error disappears. Is this as it should be or did i missed something in requiring jQuery?

**Comment by vladiim** [comment]
I had the same issue with `#=require application` in spec.js.coffee fixing it.

I am actually getting a `ReferenceError` on other resources also

When trying to go through Ryan Bate's [RailsCast on Jasmine](http://railscasts.com/episodes/261-testing-javascript-with-jasmine) I get the following error:

```
ReferenceError: CreditCard is not defined
    at [object Object].<anonymous> (http://localhost:3000/assets/credit_card_spec.js?body=1:5:22)
    at [object Object].execute (http://localhost:3000/assets/jasmine.js?body=1:1024:15)
    at [object Object].next_ (http://localhost:3000/assets/jasmine.js?body=1:2025:31)
    at http://localhost:3000/assets/jasmine.js?body=1:2015:18
```

Although app/assets/javascipts/credit_card.js.coffee has the following:

``` coffeescript
CreditCard = cleanNumber: (number) ->
  number.replace /[- ]/g, ""
```

With `#=require credit_card` in either spec.js.coffee or credit_card_spec.js.coffee not having the same effect.

**Comment by ryanb** [comment]
CoffeeScript automatically scopes its files. Try setting `this.CreditCard` so it is available globally.

**Comment by vladiim** [comment]
Thanks Ryan! I had started doing stuff like `window.CreditCard = class CreditCard` to get around the issue which didn't feel right at all.

**Comment by ryanb** [comment]
Try `class @CreditCard`. I don't know if that's a best practice, but seems to work for me.

**Comment by vladiim** [comment]
Works a treat and much nicer syntax - thanks

**Comment by vladiim** [comment]
As a point of interest for anyone reading I've been going through the prags [Coffeescipt Book](http://pragprog.com/book/tbcoffee/coffeescript) and you can also do:

``` coffeescript
class CreditCard
  # code goes here

root = exports ? window # exports for node.js global
root.CreditCard = CreditCard
```

**Comment by bradphelan** [comment]
The solution to the OP's problem is a missing

```
spec/javascripts/spec.js.coffee

#= require jquery
#= require credit_card
#= require_tree .
```

As Ryan Bates quite rightly points out in his screencast

**Comment by ohcibi** [comment]
Shouldnt jasmine do this by itself? I saw that jasmine needs jquery-1.3 to make the results on the results page foldable. I dont even need jquery in these particular steps so i think jasmine should load its jquery-1.3 with noConflict. Not sure if this is a jasmine or a jasmine-rails or a jasminerice issue.
