### ISSUE TITLE
Jasmine test running isn't available.

### ISSUE THREAD

**Issue by ejholmes** [bradphelan/jasminerice#49]
Trying to run my specs in a CI environment with the following rake task:

``` ruby
Guard::JasmineTask.new do |task|
  task.options = '-s thin -p 3000 -u http://localhost:3000/jasmine -e development'
end
```

Running `rake guard:jasmine` results in the following:

```
Guard::Jasmine starts thin test server on port 3000 in development environment.
Waiting for Jasmine test runner at http://localhost:3000/jasmine
ERROR: Jasmine test runner isn't available: end of file reached
rake aborted!
The spec couldn't be run: exit'

Tasks: TOP => guard:jasmine
(See full trace by running task with --trace)
```

The specs run without hitch when I bootup the server and hit http://localhost:3000/jasmine after running `rackup -p 3000 -s thin -E development`. Thoughts?

**Comment by dcrec1** [comment]
Did you find the problem?

**Comment by ejholmes** [comment]
I think I had to monkey patch something, but I honestly don't remember anymore. I've switched to [Konacha](https://github.com/jfirebaugh/konacha) for testing javascript in my rails apps.

**Comment by bradphelan** [comment]
I'm not actively developing rails at the moment but I merge most pull
requests on this project quickly.

**Comment by conzett** [comment]
I am having the same issue attempting to use jasminerice with Travis CI. Travis runs everything in the test environment, but it seems that jasminerice only works when running in the development environment. Starting it locally with `RAILS_ENV=test` it looks like the engine isn't properly mounted.
