### ISSUE TITLE
matchers toDelegateAndHandle and toDelegateAndHandleWith

### ISSUE THREAD

**Issue by MarioRicalde** [bradphelan/jasminerice#54]
Currently delegation methods ( `live`,  `on` ) are not working with `toHandle`, this has been implemented on jasmine-jquery. 

https://github.com/velesin/jasmine-jquery/pull/40

**Comment by jejacks0n** [comment]
Looks like that issue's been closed as not understanding how to do it.. please clarify if I'm incorrect.
