### ISSUE TITLE
Blank results page

### ISSUE THREAD

**Issue by bricker** [bradphelan/jasminerice#55]
I am just trying to get setup with JS testing, but get a blank results page no matter what I try. My setup so far is very simple:

**/spec/javascripts/spec.js.coffee**

``` coffeescript
#= require_tree ./
```

**/spec/javascripts/presentation_spec.js.coffee**

``` coffeescript
describe "Presentation", ->
    it "is alive", ->
        true
```

That's it. I just get a completely blank results page, whether I try it via Pow or Thin.

The name of this software makes it hard to google for answers!

**Comment by gfrivolt** [comment]
I noticed the same issue, using rails 3.2.8, similarly with both pow & thin an empty page is produced.

**Comment by joker-777** [comment]
Hi...any ideas about this issue? I'm experiencing the same problem...

**Comment by joker-777** [comment]
ok..got it running by disabling miniProfiler...strange

**Comment by rahul** [comment]
I faced the same issue until I noticed js errors in my chrome's console. Turns out I did not include the js libraries and my own js files in the right order.

**Comment by jejacks0n** [comment]
I'd say this should only happen in the cases where there's an error on the page that halts javascript execution.

**Comment by sulphur** [comment]
i have also blank page and this i spotted is that all js files has this "/jasmine" before which result in 404 errors... 

<script src="/jasmine/assets/spec.js?body=1"></script>

**Comment by maciejkowalski** [comment]
It is because of error in you JS file

Just open console (F12 in chrome) and debug.

After some work current version of this gem works for me.
