### ISSUE TITLE
Tests in production

### ISSUE THREAD

**Issue by nhocki** [bradphelan/jasminerice#6]
Will the test be accessible from the production environment?

I mean, will `www.example.com/jasmine` show the tests?

**Comment by bradphelan** [comment]
From the README

```
Now add a route to the end of your config.routes but only for development and test

    if ["development", "test"].include? Rails.env
        mount Jasminerice::Engine => "/jasmine" 
    end
```

Therefore it is up to you. If you want it in production then remove the conditional

**Comment by nhocki** [comment]
But the javascripts will still be compiled? (Add accessible?)

**Comment by bradphelan** [comment]
If you add the same conditional here

```
jasminerice/config/initializers/jasminerice.rb
```

then I think that will solve your problem. Test it out and if it works for you send me a pull request and I'll merge it.

**Comment by netzpirat** [comment]
You could simply load the jasminerice gem only within the test or development environment in your `Gemfile`.

```
group :test, :development do
  gem 'jasminerice'
end
```

Problem solved.

**Comment by bradphelan** [comment]
Yeah of course! That's actually what i do in my projects. Wasn't thinking when I posted above ;)
