### ISSUE TITLE
Specs with Coffeescript syntax errors halt tests, report "0 specs" unless ?debug_assets=true

### ISSUE THREAD

**Issue by bricker** [bradphelan/jasminerice#64]
I know this has been an issue before, but it doesn't seem to be solved entirely.

The known issue:

``` coffeescript
describe "SomeClass", ->
    it "fails", ->
        ,,,,,
```

> http://localhost:8000/jasmine
> 0 specs, 0 failures
> 
> http://localhost:8000/jasmine?debug_assets=true
> ExecJS::ProgramError

The ExecJS error is what I expect to see when I have a syntax error.

From Rails `config/environments/test.rb` :

``` ruby
# Allow pass debug_assets=true as a query parameter to load pages with unpackaged assets
config.assets.allow_debugging = true
```

Is this something we can fix easily? The main reason it's a bother is because I use `guard-jasmine`.

Thanks.

**Comment by jejacks0n** [comment]
Are you still dealing with this, and if so, what would you suggest as a solution?
