### ISSUE TITLE
Unable to load json fixture

### ISSUE THREAD

**Issue by chamnap** [bradphelan/jasminerice#69]
For some reasons, my spec is always failed because it could not json fixtures.

`data = loadJSONFixtures('places.json')`

➤ Error: JSONFixture could not be loaded: spec/javascripts/fixtures/json/places.json (status: error, message: undefined) in jasmine-jquery-1.4.2.js on line 269

**Comment by alexslade** [comment]
Same problem here, looks like the code to handle that doesn't actually exist yet. Will take a look tomorrow.

**Comment by alexslade** [comment]
@chamnap I've added a pull request - #75

**Comment by chamnap** [comment]
@heeton, Thanks :)

**Comment by jejacks0n** [comment]
Looks like this has been resolved.  Closing. =)
