### ISSUE TITLE
jasmine.rice undefined

### ISSUE THREAD

**Issue by adampash** [bradphelan/jasminerice#70]
I'm trying to follow the [compatibility with require.js](https://github.com/bradphelan/jasminerice#compatibility-with-requirejs) instructions, but when I set:

``` javascript
jasmine.rice.autoExecute = false
```

I get an error in the js console when jasmine runs:

```
Uncaught TypeError: Cannot set property 'autoExecute' of undefined 
```

Any idea what I might be doing wrong here? I'm trying to get require.js support going in my tests, but this seems to be standing in the way.

**Comment by jejacks0n** [comment]
Do you have any further information on this?
