### ISSUE TITLE
Remove dependency on haml

### ISSUE THREAD

**Issue by christiannelson** [bradphelan/jasminerice#80]
Some conversation is happening on another related issue https://github.com/bradphelan/jasminerice/pull/44#issuecomment-10699856, that's closed. Figured it was worth creating a new issue to revive this. While I'm asking for the same thing, the reasoning is different. From the other issue:

Any chance you reconsider this, but for a different reason? Every project that uses jasmine-rice -- which is quite a few, it's good stuff -- end up depending on haml (weighing in at 370k+) whether they use it or not. We no longer use haml (in favor of slim), but haml ends up being installed and loaded anyway. Lots of gems include things that either aren't really critical for the normal operation of the gem (not this case) or they use something for a thin sliver of functionality (this case).

The end result is that a simple rails project bloats up to 50+ gems (directly and transitively), with some deps not really being necessary (because they're there to support obscure features) or they're included to and barely used.

This bloat is giving rails and the rails community a bad rep, which is unfortunate.

As @nick-desteffen mentioned, haml is saving you only a few lines of code in one file. Is that really worth dragging along an extra 370k gem? Thanks.

**Comment by nick-desteffen** [comment]
@christiannelson Doesn't look like @bradphelan is willing to remove the dependency.  I forked and removed Haml. I plan on periodically merging in changes from upstream.

https://github.com/nick-desteffen/jasminerice

**Comment by ngan** [comment]
:+1:

**Comment by jejacks0n** [comment]
This will be fixed when we merge.

**Comment by prashantrajan** [comment]
:+1:
