### ISSUE TITLE
Configurable spec filenames?

### ISSUE THREAD

**Issue by jdickey** [bradphelan/jasminerice#81]
## Background

I'm moving a project over from another tool ([TestTrack](https://github.com/quickleft/test_track), which has been stuck at "Version 0.0.4" for a year now). I have several score spec files named using camelCase rather than underscores. Given the notation in `spec.js.coffee' that

> This pulls in all your specs from the javascripts directory into Jasmine:
> 
> spec/javascripts/__spec.js.coffee
> spec/javascripts/__spec.js
> spec/javascripts/*_spec.js.erb
> IT IS UNLIKELY THAT YOU WILL NEED TO CHANGE THIS FILE

it's actually necessary that I change that file, and bring in all my files named, e.g., `Something/Or/Other/FooBarBazSpec.js.coffee`.
## The New Feature

It Would Be Very Nice if there were some configuration option available so that `jasminerice` could change its default spec file pattern. I haven't (yet) delved into your code (being scalp-deep in my own), but would that be terribly difficult or burdensome?

**Comment by jejacks0n** [comment]
You should be able to require your files pretty easily.  Since Jasminerice uses a manifest style for loading files you're free to require what you want to load in the spec.js.coffee.
