### ISSUE TITLE
Can't expand results

### ISSUE THREAD

**Issue by dnagir** [bradphelan/jasminerice#87]
1. Open the the `/jasmine?pp=skip` (`pp=skip` just to ignore the MiniProfiler).
2. Click on the link to expand the results ("265 specs" or "6 failing").

No results are show, and it doesn't look like it works.

Using `0.0.10` version of jasminerice.

![Screen Shot 2013-01-14 at 3 20 08 PM](https://f.cloud.github.com/assets/195035/63726/bc3948c4-5e01-11e2-9ee3-48e7b7b832c9.png)

**Comment by dnagir** [comment]
I think the reason is that one of the tests fixtures was using the `results` css class, which messes up with the neweer jasmine interface.

Don't know why jasmine isn't using any prefixes or anything like that :(

So I suppose this can be closed since it is not really a jasminerice issue (at least from what I can see).

**Comment by jejacks0n** [comment]
Thanks for the heads up. =)
