### ISSUE TITLE
Unable to filter the directories from which spec files are loaded from.

### ISSUE THREAD

**Issue by colin-jack** [bradphelan/jasminerice#9]
I'm using the guard to compile my coffeescript:

guard 'coffeescript', :input => 'spec/javascripts', :output => 'spec/javascripts/compiled'

I do this so livereload will reload the jasmine tests when I change the JS. I'm also using jasminerice though and when I do this I get the tests included twice. I think this is caused by this line in spec.js.coffee:
# =require_tree ./

I tried changing the spec.js.coffee to just bring in the specs from the folders I want:
# =require_tree ./compiled
# =require_tree ./helpers

Unfortunately when I do that the javascript I'm testing (under /app/assets/javascripts) no longer gets brought in (which surprised me a little).

**Comment by colin-jack** [comment]
I was thinking, this could just be a documentation issue. 

One similiar issue...I've defined coffeescript files with test utility code but I've not worked out how to get them to work properly with jasminerice and its use of the asset pipeline. Its possible I'm going at it the wrong way though which made me think it might be worth documenting the preferred approach.

**Comment by bradphelan** [comment]
On Sat, Sep 10, 2011 at 4:39 PM, Colin Jack <
reply@reply.github.com>wrote:

> I'm using the guard to compile my coffeescript:
> 
> guard 'coffeescript', :input => 'spec/javascripts', :output =>
> 'spec/javascripts/compiled'

You shouldn't need to compile anything under Rails 3.1 that is the whole
point of the asset pipeline. I'd suggest there is a problem with livereload
if you feel you need to do this.

B

**Comment by colin-jack** [comment]
Your quite right when I think about it sorry.
