### ISSUE TITLE
Multiple Suites wiki contains incorrect information regarding routing

### ISSUE THREAD

**Issue by cebartling** [bradphelan/jasminerice#97]
The [Multiple Suites wiki](https://github.com/bradphelan/jasminerice/wiki/Multiple-Suites) contains configuration for routes.rb that is incorrect.  Specifically, the the **:suite path** variable will not work with the Jasminerice::SpecController#index method:

``` ruby
    def index
      @specenv = params[:environment].try(:concat, "_spec") || "spec"
    end
```

I'd like to see the continued use of the :suite parameter and change the SpecController method, replacing **:environment** with **:suite**.

**Comment by jejacks0n** [comment]
Can you provide more information -- I don't understand exactly what you mean.  Thanks.

**Comment by cebartling** [comment]
Absolutely!!  The wiki documentation for Multiple Suites states using the following configuration in your **routes.rb** file:

``` ruby
if %w(development test).include? Rails.env
  mount Jasminerice::Engine => "/jasmine/:suite"
end
```

Note the parameter placeholder in the URL above--it's specifying **:suite**.  With this configuration in place, the Jasminerice::SpecController#index method will be invoked with a params key of **:suite**.  However, that is not the params key that the controller is expecting; it's expecting **:environment**.  

If you're like me, investigating this functionality for the first time and following the directions in the wiki, it won't work.  The easy fix is to update the wiki to specify a params key of **:enviroment**.  The better longer term fix would be to change the SpecController to use the **:suite** key instead.  The **:environment** key is misleading--it makes it seem like we're asking for the Rails environment here.  We are not--we are asking for a custom spec suite name.  There may be many different suites that this SpecController must handle, and none of them are dependent on the concept of environment (except that the Jasminerice::Engine is only mounted in the _development_ and _test_ environments).  Let me know if you need more context.  Should be easy to resolve in the short and long terms.

**Comment by jejacks0n** [comment]
Ok, so I understand now.. You're using an old release of the gem.  I've not been able to get @bradphelan to release it, so you'll have to point your gem to master using:

``` ruby
gem "jasminerice", git: "https://github.com/bradphelan/jasminerice.git"
# or
gem "jasminerice", github: "bradphelan/jasminerice"
```

We discuss the topic further and I provide alternatives [here](https://github.com/bradphelan/jasminerice/issues/86).

**Comment by jejacks0n** [comment]
Just to clarify, the documentation is accurate with master -- not the released gem.  I've updated the readme to encourage you to point the gem at master.

**Comment by cebartling** [comment]
Thanks @jejacks0n.  I will point to master for the short term, but I'm bit concerned by the recent news about Jasminerice not being actively maintained and the feeling that it's currently floating out at sea without a skipper.  Thanks for the information about Teabag and others.  I will probably end up migrating to something that will be more actively maintained going forward.

**Comment by cebartling** [comment]
Verified that pointing to master fixes the issue.  Closing the issue.
