### ISSUE TITLE
Use relative roots for fixturesPath

### ISSUE THREAD

**Issue by longlostnick** [bradphelan/jasminerice#98]
I ran into an issue when testing a backbone.js based app where once I changed the browsers pushState fixtures wouldn't load anymore because the fixturesPaths are all set to relative urls.

Right now my fix is to include the following in my spec_helper:

``` javascript
jasmine.getFixtures().fixturesPath = '/jasmine/fixtures'
jasmine.getStyleFixtures().fixturesPath = '/jasmine/fixtures'
jasmine.getJSONFixtures().fixturesPath = '/jasmine/fixtures/json'
```

However, would it make sense to just do this by default?

**Comment by jejacks0n** [comment]
Yes, it would make sense.. would you like to submit a pull request?
